//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSMessengerClient.ServiceUserRepository {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/MessengerDomain")]
    [System.SerializableAttribute()]
    public partial class UserProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfConnectionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfConnections {
            get {
                return this.NumberOfConnectionsField;
            }
            set {
                if ((this.NumberOfConnectionsField.Equals(value) != true)) {
                    this.NumberOfConnectionsField = value;
                    this.RaisePropertyChanged("NumberOfConnections");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUserRepository.IWSUserProfile")]
    public interface IWSUserProfile {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUserProfile/GetUserProfile", ReplyAction="http://tempuri.org/IWSUserProfile/GetUserProfileResponse")]
        WSMessengerClient.ServiceUserRepository.UserProfile GetUserProfile(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUserProfile/GetUserProfile", ReplyAction="http://tempuri.org/IWSUserProfile/GetUserProfileResponse")]
        System.Threading.Tasks.Task<WSMessengerClient.ServiceUserRepository.UserProfile> GetUserProfileAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUserProfile/CreateUserProfile", ReplyAction="http://tempuri.org/IWSUserProfile/CreateUserProfileResponse")]
        void CreateUserProfile(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUserProfile/CreateUserProfile", ReplyAction="http://tempuri.org/IWSUserProfile/CreateUserProfileResponse")]
        System.Threading.Tasks.Task CreateUserProfileAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUserProfile/ModifyUserProfile", ReplyAction="http://tempuri.org/IWSUserProfile/ModifyUserProfileResponse")]
        bool ModifyUserProfile(string profile, string newUserName, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUserProfile/ModifyUserProfile", ReplyAction="http://tempuri.org/IWSUserProfile/ModifyUserProfileResponse")]
        System.Threading.Tasks.Task<bool> ModifyUserProfileAsync(string profile, string newUserName, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUserProfile/DeleteUserProfile", ReplyAction="http://tempuri.org/IWSUserProfile/DeleteUserProfileResponse")]
        bool DeleteUserProfile(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUserProfile/DeleteUserProfile", ReplyAction="http://tempuri.org/IWSUserProfile/DeleteUserProfileResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserProfileAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSUserProfileChannel : WSMessengerClient.ServiceUserRepository.IWSUserProfile, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSUserProfileClient : System.ServiceModel.ClientBase<WSMessengerClient.ServiceUserRepository.IWSUserProfile>, WSMessengerClient.ServiceUserRepository.IWSUserProfile {
        
        public WSUserProfileClient() {
        }
        
        public WSUserProfileClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSUserProfileClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSUserProfileClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSUserProfileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WSMessengerClient.ServiceUserRepository.UserProfile GetUserProfile(string username) {
            return base.Channel.GetUserProfile(username);
        }
        
        public System.Threading.Tasks.Task<WSMessengerClient.ServiceUserRepository.UserProfile> GetUserProfileAsync(string username) {
            return base.Channel.GetUserProfileAsync(username);
        }
        
        public void CreateUserProfile(string username, string password) {
            base.Channel.CreateUserProfile(username, password);
        }
        
        public System.Threading.Tasks.Task CreateUserProfileAsync(string username, string password) {
            return base.Channel.CreateUserProfileAsync(username, password);
        }
        
        public bool ModifyUserProfile(string profile, string newUserName, string newPassword) {
            return base.Channel.ModifyUserProfile(profile, newUserName, newPassword);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyUserProfileAsync(string profile, string newUserName, string newPassword) {
            return base.Channel.ModifyUserProfileAsync(profile, newUserName, newPassword);
        }
        
        public bool DeleteUserProfile(string username) {
            return base.Channel.DeleteUserProfile(username);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserProfileAsync(string username) {
            return base.Channel.DeleteUserProfileAsync(username);
        }
    }
}
